services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red:/data
    depends_on:
      - mqtt
      - ingestion-service

  simulation:
    build: ../simulations/raw-data-generator
    container_name: simulation
    environment:
      - GENERATOR_MODE=all
    depends_on:
      - mqtt

  ingestion-service:
    build:
      context: ..
      dockerfile: services/ingestion-service/Dockerfile
    container_name: ingestion-service
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    